# Generated by Django 6.1 on 2026-09-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='Example',
        ),
    ]
